# Test 1

In [ ]:
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
age = input("Enter your age: ")

print(f'''My name is {first_name} {last_name}. I am {age} years old.''')
print("My name is " + first_name + " " + last_name + ". I am " + age + " years old.")

Enter your first name: Abdul
Enter your last name: Subhan
Enter your age: 17
My name is Abdul Subhan. I am 17 years old.
My name is Abdul Subhan. I am 17 years old.


In [ ]:
var_1 = "Hello"
var_2 = 50
var_3 = 7.89
print(type(var_1))
print(type(var_2))
print(type(var_3))

<class 'str'>
<class 'int'>
<class 'float'>


# Test 2

In [ ]:
num = int(input("Enter your number: "))

num += 10
num *= 2
num -= 5
num /= 3
num *= 3.2
num //= 1

print(f'''The final value of the variable is: {num}''')

Enter your number: 5
The final value of the variable is: 26.0


# Test 3

In [ ]:
# Test 3

name = input("Enter Your Name:")
father_name = input("Enter Your Father Name:")
gender = input("Enter Your Gender:")
age = int(input("Enter Your Age:"))
area_code = input("Enter Your Area Code:")

if age >= 18:
   print("You are eligible for vote")

   if area_code == 432:
      print("Your voting area is malir")

   else:
        print("Your voting area is other")

else:
     print("You are not eligible for vote")

Enter Your Name:Abdul Subhan
Enter Your Father Name:Saghir Muhammad
Enter Your Gender:Male
Enter Your Age:17
Enter Your Area Code:432
You are not eligible for vote


# Test 4

In [ ]:
password = input("Enter Your Password: ")

if len(password) < 6:
   print("Weak Password")

elif len(password) >= 6 and len(password) <= 10:
     print("Modrate Password")

elif len(password) > 10:
     print("Strong Password")

elif " " in password:
   print("Invalid Password")

else:
     print("Correct Password")

Enter Your Password: MASubhan2110
Strong Password


# Test 5

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Even_numbers = numbers[1::2]

print(Even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

odd_numbers = numbers[::2]

print(odd_numbers)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


# Test 6

In [ ]:
students = {1:{"name":"emma", "age":27, "roll no.":12345}, 2:{"name":"mic", "age":22, "roll no.":54321}}

print(students[1]["age"])

27


# Test 7

In [ ]:
for i in range(5):
    print("* " * 5)

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [ ]:
for i in range(5):
    print(" " * (5 - i) + "*" * (i + 1))

     *
    **
   ***
  ****
 *****


# Test 8

In [ ]:
i = 0
while True:
    number = int(input("Enter the number: "))

    if number < 0:
        print("Negative Value")
        break
    else:
        i += number
print(i)

Enter the number: 5
Enter the number: 0
Enter the number: -1
Negative Value
5


# Test 9

In [ ]:
numbers = int(input("Enter the number: "))
sum_of_numbers = sum([i for i in range(1, numbers + 1)])
print(sum_of_numbers)

Enter the number: 5
15


In [ ]:
prime_numbers = [i for i in range(25, 50) if all(i % j != 0 for j in range(2, i))]
print(prime_numbers)

[29, 31, 37, 41, 43, 47]


# Test 10

In [ ]:
def factorial(number):
  i = 1
  while number > 0:
    i *= number
    number -= 1
  return i

number = int(input("Enter the number: "))
print(factorial(number))

Enter the number: 5
120


#Test 11

In [ ]:
Table = lambda x : [x * i for i in range(1, 11)]

print(Table(2))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


# Test 12

In [ ]:
class Humans:
    def eat(self):
        print("This is human food.")

class Human(Humans):
    def roti(self):
        print("This is roti.")

human = Human()
human.eat()
human.roti()

This is human food.
This is roti.


In [ ]:
class Operation:
    def __init__(self, a, b):
        self.__a = a
        self.__b = b

    def add(self):
        return self.__a + self.__b

result = Operation(2, 3)
result.add()

5

# Test 13

In [ ]:
import numpy as np

arr = np.arange(9)
array = arr.reshape(3,3)
print(array)

matrix = array * array
print(matrix)

print(matrix[1][2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
25


# Test 14

In [95]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name":["Abdul Subhan", "Abdullah", "Abdul Rehman", "Areeba", "Eman", "Ummi", "Ahmad", "Bilal", "Usman", "Owais", "Arsil", "Aman", "Asad", "Umer", "Umair", "Asim", "Shahid", "Tahir", "Adan", "Sejeel", "Ahmad"],
    "Roll No":[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 27, 120, 107],
    "Math":[76, 82, 98, 69, 56, 81, 98, 52, 61, 72, 76, np.nan, 69, 95, np.nan, 46, 52, np.nan, 27, 82, 98],
    "English":[90, 95, 86, np.nan, 52, 68, 79, 58, 92, 87, np.nan, 79, 64, 52, 89, 74, np.nan, 96, 27, 69, 79],
    "Physics":[95, 82, np.nan, 64, 82, 16, 24, 99, np.nan, 52, 89, 76, 94, np.nan, 71, 79, 24, 64, 27, 29, 24],
    "Chemistry":[89, np.nan, 92, 82, 46, 38, 89, 57, np.nan, 38, 52, 99, 68, 82, 57, 73, 17, 20, 27, 93, 89],
    "Islamiat":[82, 96, 46, np.nan, 78, 100, 52, np.nan, 100, 93, 57, 71, 62, 68, np.nan, 16, 81, np.nan, 27, 29, 52],
})

In [96]:
nan = df.isnull().sum()
nan

Name         0
Roll No      0
Math         3
English      3
Physics      3
Chemistry    2
Islamiat     4
dtype: int64

In [97]:
duplicate = df.duplicated().sum()
duplicate

1

In [98]:
df = df.dropna()
df

Name  Roll No  Math  English  Physics  Chemistry  Islamiat
0   Abdul Subhan      101  76.0     90.0     95.0       89.0      82.0
4           Eman      105  56.0     52.0     82.0       46.0      78.0
5           Ummi      106  81.0     68.0     16.0       38.0     100.0
6          Ahmad      107  98.0     79.0     24.0       89.0      52.0
9          Owais      110  72.0     87.0     52.0       38.0      93.0
12          Asad      113  69.0     64.0     94.0       68.0      62.0
15          Asim      116  46.0     74.0     79.0       73.0      16.0
18          Adan       27  27.0     27.0     27.0       27.0      27.0
19        Sejeel      120  82.0     69.0     29.0       93.0      29.0
20         Ahmad      107  98.0     79.0     24.0       89.0      52.0

In [100]:
df = df.drop_duplicates()
df

Name  Roll No  Math  English  Physics  Chemistry  Islamiat
0   Abdul Subhan      101  76.0     90.0     95.0       89.0      82.0
4           Eman      105  56.0     52.0     82.0       46.0      78.0
5           Ummi      106  81.0     68.0     16.0       38.0     100.0
6          Ahmad      107  98.0     79.0     24.0       89.0      52.0
9          Owais      110  72.0     87.0     52.0       38.0      93.0
12          Asad      113  69.0     64.0     94.0       68.0      62.0
15          Asim      116  46.0     74.0     79.0       73.0      16.0
18          Adan       27  27.0     27.0     27.0       27.0      27.0
19        Sejeel      120  82.0     69.0     29.0       93.0      29.0

In [103]:
df["Total"] = df["Math"] + df["English"] + df["Physics"] + df["Chemistry"] + df["Islamiat"]
df

Name  Roll No  Math  English  Physics  Chemistry  Islamiat  Total  \
0   Abdul Subhan      101  76.0     90.0     95.0       89.0      82.0  432.0   
4           Eman      105  56.0     52.0     82.0       46.0      78.0  314.0   
5           Ummi      106  81.0     68.0     16.0       38.0     100.0  303.0   
6          Ahmad      107  98.0     79.0     24.0       89.0      52.0  342.0   
9          Owais      110  72.0     87.0     52.0       38.0      93.0  342.0   
12          Asad      113  69.0     64.0     94.0       68.0      62.0  357.0   
15          Asim      116  46.0     74.0     79.0       73.0      16.0  288.0   
18          Adan       27  27.0     27.0     27.0       27.0      27.0  135.0   
19        Sejeel      120  82.0     69.0     29.0       93.0      29.0  302.0   

    Percentage  
0         86.4  
4         62.8  
5         60.6  
6         68.4  
9         68.4  
12        71.4  
15        57.6  
18        27.0  
19        60.4

In [104]:
df["Percentage"] = df["Total"] * 100 / 500
df

Name  Roll No  Math  English  Physics  Chemistry  Islamiat  Total  \
0   Abdul Subhan      101  76.0     90.0     95.0       89.0      82.0  432.0   
4           Eman      105  56.0     52.0     82.0       46.0      78.0  314.0   
5           Ummi      106  81.0     68.0     16.0       38.0     100.0  303.0   
6          Ahmad      107  98.0     79.0     24.0       89.0      52.0  342.0   
9          Owais      110  72.0     87.0     52.0       38.0      93.0  342.0   
12          Asad      113  69.0     64.0     94.0       68.0      62.0  357.0   
15          Asim      116  46.0     74.0     79.0       73.0      16.0  288.0   
18          Adan       27  27.0     27.0     27.0       27.0      27.0  135.0   
19        Sejeel      120  82.0     69.0     29.0       93.0      29.0  302.0   

    Percentage  
0         86.4  
4         62.8  
5         60.6  
6         68.4  
9         68.4  
12        71.4  
15        57.6  
18        27.0  
19        60.4